### ISSUE TITLE
Rectangular Boards: Source of Errors?

### ISSUE THREAD

**Issue by Bram28** [Bram28/LEGUP#73]
Rectangular boards seem to cause some errors ... in Nurikabe at least ... other puzzles?

**Comment by mmellone** [comment]
I discovered it was some old rules that used cells[x][y] instead of cells[y][x], this flipped the width and height and thus caused index out of bounds errors with the rectangular boards. I changed these rules (fill in black, fill in white, and surround region) to use contradictions like the other rules. It also saved a few hundred lines of code and probably made them run a little faster (some of the old algorithms were a little costly I believe), so it was a good change.

1fc21fedac267c8989f9c2cac3fa638cd0694d90

**Comment by Bram28** [comment]
Nijce, good work!!

Bram
________________________________________
